[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build --filter kyuzo"]

[start]
cmd = "cd apps/kyuzo && pnpm run start"

[variables]
NODE_ENV = "production"
